name: puzzle
version: 0.1.0-beta.2
description: Visual XAML for Dart/Flutter, Use puzzle for developing visual dart/flutter app.
homepage: https://github.com/visual-dart/puzzle
author: bigmogician<bigmogician@outlook.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: ^0.38.1
  glob: ^1.1.7
  xml: ^3.4.0
  yaml: ^2.1.15
  path: ^1.6.2
  dart_style: ^1.2.10
  front_end: ^0.1.21
  watcher: ^0.9.7
  ansicolor: ^1.0.2

executables:
  puzzle: puzzle
